name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or the branch you want to trigger the pipeline on

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # or the version of Python you're using
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # adjust the path if necessary
          
      - name: Run tests
        run: |
          python -m unittest discover  # adjust the command to run your tests
